name: Auto Set Start Date on Branch Create

on:
  create:
    branches:
      - '*'
permissions:
  issues: write
  contents: read
  
jobs:
  set_start_date:
    runs-on: ubuntu-latest

    steps:
      - name: Set Start Date field in ProjectV2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          ISSUE_NUMBER=$(echo "$BRANCH" | grep -oE '[0-9]+' | head -n 1)
          echo "Issue Number: $ISSUE_NUMBER"
         
