name: Set startDate when branch created

on:
  create:
    branches:
      - '**'

jobs:
  setStartDate:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue number from branch name
        id: extract
        run: |
          branch="${GITHUB_REF_NAME}"
          if [[ "$branch" =~ ([0-9]+) ]]; then
            echo "issue_number=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi

      - name: Set startDate on issue
        if: steps.extract.outputs.issue_number != ''
        run: |
          issue_number=${{ steps.extract.outputs.issue_number }}
          date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          gh api repos/${{ github.repository }}/issues/$issue_number \
            --method PATCH \
            -f labels="In Progress" \
            -f body="Started at $date"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
